import pandas as pd
import sys
import os

import test_utils
from filegen_utils import *
from IAA import *

sys.path.append('../../')

#1-N users highlight the same thing, see if agreement score changes
def test_user_highlighting_consensus(config, tmpdir):
    test_path = test_utils.make_test_directory(config, 'test_highlight_consensus')
    for i in range(1, 10):
        #source_task_id generated by smashing keyboard
        dh = datahunt(out_folder=test_path, source_task_id = 'jamietest' + str(i))
        for j in range(i):
            dh.add_row({'answer_label': 'T1.Q2.A2', 'namespace': 'Covid_Evidence2020_03_21', 'contributor_uuid':'human' + str(j),  'start_pos':0, 'end_pos':1})
        for j in range(i, 10):
            dh.add_row({'answer_label': 'T1.Q2.A2', 'namespace': 'Covid_Evidence2020_03_21', 'contributor_uuid':'human' + str(j),  'start_pos':2*j, 'end_pos':(2*j)+1})
        fin_path = dh.export()
        data_path = config['data_dir']
        schema_path = data_path+'/schemas'

    iaa_out = calc_agreement_directory(test_path, schema_path, config['IAA_config_dir'], test_utils.texts_dir, outDirectory = tmpdir)
    i = 1
    for root, dir, files in os.walk(iaa_out):
        for file in files:
            out_df  = pd.read_csv(os.path.join(iaa_out, file), encoding='utf-8')
            #Why does this not change??
            print(out_df['highlighted_indices'].tolist())
            #Currently, agreement score does not change based on highlight indices.
            agree_score = out_df['agreement_score'].tolist()[1]
            assert agree_score == 1
            print("When", i, "users agree, agreement score is:", agree_score)
            i += 1

#N users on schema v1 and N users on schema v2--ensure output rows identical
def test_diff_schemas(config, tmpdir):
    test_path = test_utils.make_test_directory(config, 'test_diff_schemas')
    #source_task_id generated by smashing keyboard
    dh = datahunt(out_folder=test_path, source_task_id = 'jamietest')
    dh.add_row({'answer_label': 'T1.Q2.A2', 'namespace': 'Covid_Evidence2020_03_21', 'contributor_uuid':'Michael'})
    dh.add_row({'answer_label': 'T1.Q2.A2', 'namespace': 'Covid_Evidence2020_03_21', 'contributor_uuid':'Dwight'})
    fin_path = dh.export()
    data_path = config['data_dir']
    schema_path = data_path+'/schemas'
    #Directory to new schemas here
    new_schema_path = 'newSchemas'

    iaa_out = calc_agreement_directory(test_path, schema_path, config['IAA_config_dir'], test_utils.texts_dir, outDirectory = tmpdir)
    for root, dir, files in os.walk(iaa_out):
        for file in files:
            out_df  = pd.read_csv(os.path.join(iaa_out, file), encoding='utf-8')

    iaa_out2 = calc_agreement_directory(test_path, new_schema_path, config['IAA_config_dir'], test_utils.texts_dir, outDirectory = tmpdir)
    for root, dir, files in os.walk(iaa_out2):
        for file in files:
            out_df2  = pd.read_csv(os.path.join(iaa_out2, file), encoding='utf-8')

    assert out_df.equals(out_df2)
