from filegen_utils import IAA_task
import pytest
import json
import os
import test_utils
from filegen_utils import *
from IAA import *

def test_highlights(config, tmpdir):
    test_path = test_utils.make_test_directory(config, 'test_iaa_highlights')
    # source_task_id generated by smashing keyboard
    dh = datahunt(out_folder=test_path, source_task_id='highlights')
    for i in range(8):
        dh.add_row({'answer_label': 'T1.Q2.A' + str(i + 1), 'namespace': 'Covid_Evidence2020_03_21',
                    'contributor_uuid': 'Daniel' + str(i), 'start_pos': i, 'end_pos': i + 10})
    fin_path = dh.export()

    data_path = config['data_dir']
    schema_path = data_path + '/schemas'

    iaa_out = calc_agreement_directory(test_path, schema_path, config['IAA_config_dir'], test_utils.texts_dir,
                                       outDirectory=tmpdir)
    print(iaa_out)
    for root, dir, files in os.walk(iaa_out):
        for file in files:
            # should be only 1 file for this case, so just run it on the only one
            # if there's more than 1 then you can get fancy
            out_df = pd.read_csv(os.path.join(iaa_out, file), encoding='utf-8')
            print(out_df["highlighted_indices"])
            temp = out_df["highlighted_indices"].tolist()
            for i in range(8):
                assert temp[i][i] == i
            print("++++++++++++++")
            print(out_df['coding_perc_agreement'].tolist())