import sys
import os
import pandas as pd

import test_utils
from filegen_utils import *
from Dependency import *
import conftest

#REFERENCE: in Evidence, parents = {1.1:[2], 1.2:[2], 2.1:[4], 2.5:[4,5], 2.8:[3], 5.1:[6], 5.2:[6], 5.3:[6], 9.1:[10,11], 9.2:[10,11]}
def test_dep_sample(config):
    iaa_files_path = test_utils.make_test_directory(config, 'dep_basic')
    out_path = test_utils.make_test_directory(config, 'dep_basic_out')
    # source_task_id generated by smashing keyboard
    iaa = IAA_task(out_folder=iaa_files_path, source_task_id='boogaboga')
    iaa.add_row({"namespace":"Covid_Evidence2020_03_21", "question_Number":1, "agreed_Answer":1,  "agreement_score":.5, 'highlighted_indices':test_utils.make_highlight_indices(10,30)})
    iaa.add_row({"namespace": "Covid_Evidence2020_03_21", "question_Number": 2, "agreed_Answer": 1,  "agreement_score": .5})
    iaa.add_row({"namespace": "Covid_Evidence2020_03_21", "question_Number": 4, "agreed_Answer": 1,  "agreement_score": .5})
    fin_path = iaa.export()
    data_path = config['data_dir']
    schema_path = data_path + '/schemas'
    dh_path = None #doesn't get used by dependency but is still an argument

    eval_dependency(dh_path, iaa_files_path, schema_path, out_path)

    for root, dir, files in os.walk(out_path):
        for file in files:
            #should be only 1 file for this case, so just run it on the only one
            # if there's more than 1 then you can get fancy
            out_df  = pd.read_csv(os.path.join(out_path, file), encoding='utf-8')

def test_dep_sample2(config):
    iaa_files_path = test_utils.make_test_directory(config, 'dep_basic2')
    out_path = test_utils.make_test_directory(config, 'dep_basic2_out')
    # source_task_id generated by smashing keyboard
    iaa = IAA_task(out_folder=iaa_files_path, source_task_id='boogabogas')
    iaa.add_row({"namespace":"Covid_Evidence2020_03_21", "question_Number":1, "agreed_Answer":1,  "agreement_score":.5})
    iaa.add_row({"namespace":"Covid_Evidence2020_03_21", "question_Number":1, "agreed_Answer":2,  "agreement_score":1})
    iaa.add_row({"namespace": "Covid_Evidence2020_03_21", "question_Number": 2, "agreed_Answer": 1,  "agreement_score": 1})
    iaa.add_row({"namespace": "Covid_Evidence2020_03_21", "question_Number": 2, "agreed_Answer": 2,  "agreement_score": .5})
    fin_path = iaa.export()
    data_path = config['data_dir']
    schema_path = data_path + '/schemas'
    dh_path = None #doesn't get used by dependency but is still an argument

    eval_dependency(dh_path, iaa_files_path, schema_path, out_path)

    for root, dir, files in os.walk(out_path):
        for file in files:
            #should be only 1 file for this case, so just run it on the only one
            # if there's more than 1 then you can get fancy
            out_df  = pd.read_csv(os.path.join(out_path, file), encoding='utf-8')
